var possibleWords1 = [
  { name: "HUND", image: "./images/level1/hund.png" },
  { name: "KUH", image: "./images/level1/kuh.png" },
  { name: "OHR", image: "./images/level1/ohr.png" },
  { name: "NASE", image: "./images/level1/nase.png" },
  { name: "EULE", image: "./images/level1/eule.png" },
  { name: "ROT", image: "./images/level1/rot.png" },
  { name: "BALL", image: "./images/level1/ball.png" },
  { name: "BLAU", image: "./images/level1/blau.png" },
  { name: "AUTO", image: "./images/level1/auto.png" },
  { name: "HAND", image: "./images/level1/hand.png" },

  { name: "TOR", image: "./images/level1/tor.png" },
  { name: "BAUM", image: "./images/level1/baum.png" },
  { name: "BABY", image: "./images/level1/baby.png" },
  { name: "BUCH", image: "./images/level1/buch.png" },
  { name: "HAUS", image: "./images/level2/haus.png" },
  { name: "GANS", image: "./images/level2/gans.png" },
  { name: "GELD", image: "./images/level2/geld.png" },
  { name: "MAUS", image: "./images/level2/maus.png" },
  { name: "BROT", image: "./images/level2/brot.png" },
  { name: "HERZ", image: "./images/level2/herz.png" },

  { name: "MUND", image: "./images/level2/mund.png" },
]
var possibleWords2 = [
  { name: "KUCHEN", image: "./images/level1/kuchen.png" },
  { name: "BIENE", image: "./images/level1/biene.png" },
  { name: "FUCHS", image: "./images/level1/fuchs.png" },
  { name: "HAARE", image: "./images/level1/haare.png" },
  { name: "TASSE", image: "./images/level1/tasse.png" },
  { name: "FISCH", image: "./images/level1/fisch.png" },
  { name: "SONNE", image: "./images/level1/sonne.png" },
  { name: "MILCH", image: "./images/level1/milch.png" },
  { name: "FLAGGE", image: "./images/level1/flagge.png" },
  { name: "KATZE", image: "./images/level1/katze.png" },

  { name: "STERN", image: "./images/level1/stern.png" },
  { name: "PFERD", image: "./images/level2/pferd.png" },
  { name: "WASSER", image: "./images/level2/wasser.png" },
  { name: "ZEBRA", image: "./images/level2/zebra.png" },
  { name: "BLUME", image: "./images/level2/blume.png" },
  { name: "KREUZ", image: "./images/level2/kreuz.png" },
  { name: "WOLKE", image: "./images/level2/wolke.png" },
  { name: "APFEL", image: "./images/level2/apfel.png" },
  { name: "STUHL", image: "./images/level2/stuhl.png" },
  { name: "HANDY", image: "./images/level2/handy.png" },

  { name: "PAPIER", image: "./images/level2/papier.png" },
  { name: "FLUSS", image: "./images/level2/fluss.png" },
  { name: "KRONE", image: "./images/level2/krone.png" },
  { name: "KIRCHE", image: "./images/level2/kirche.png" },
  { name: "PALME", image: "./images/level3/palme.png" },
  { name: "ZAHLEN", image: "./images/level3/zahlen.png" },
  { name: "BRILLE", image: "./images/level3/brille.png" },
  { name: "LEHRER", image: "./images/level3/lehrer.png" },
  { name: "DELFIN", image: "./images/level3/delfin.png" },
  { name: "BLASEN", image: "./images/level3/blasen.png" },
]

var possibleWords3 = [
  { name: "SCHWEIN", image: "./images/level1/schwein.png" },
  { name: "BAUERNHOF", image: "./images/level1/bauernhof.png" },
  { name: "POLIZEI", image: "./images/level2/polizei.png" },
  { name: "ROBOTER", image: "./images/level2/roboter.png" },
  { name: "SCHLANGE", image: "./images/level2/schlange.png" },
  { name: "SCHNECKE", image: "./images/level2/schnecke.png" },
  { name: "KIRSCHE", image: "./images/level2/kirsche.png" },
  { name: "SPIEGEL", image: "./images/level2/spiegel.png" },
  { name: "FLUGZEUG", image: "./images/level2/flugzeug.png" },
  { name: "SCHWARZ", image: "./images/level2/schwarz.png" },

  { name: "BATTERIE", image: "./images/level3/batterie.png" },
  { name: "DRUCKER", image: "./images/level3/drucker.png" },
  { name: "GIRAFFE", image: "./images/level3/giraffe.png" },
  { name: "SECHZEHN", image: "./images/level3/sechzehn.png" },
  { name: "BASEBALL", image: "./images/level3/baseball.png" },
  { name: "KALENDAR", image: "./images/level3/kalendar.png" },
  { name: "COMPUTER", image: "./images/level3/computer.png" },
  { name: "ACHTZEHN", image: "./images/level3/achtzehn.png" },
  { name: "FUSSBALL", image: "./images/level3/fussball.png" },
  { name: "DREIZEHN", image: "./images/level3/dreizehn.png" },

  { name: "ELEFANT", image: "./images/level3/elefant.png" },
  { name: "PINGUIN", image: "./images/level3/pinguin.png" },
  { name: "SPAGHETTI", image: "./images/level3/spaghetti.png" },
]

  // { name: "SEAHORSE", image: "./images/level3/seahorse.png" },
  //{ name: "FIRE", image: "./images/level1/fire.png" },


