var possibleWords1 = [
  { name: "HUND", image: "./images/level1/hund.png" },
  { name: "KUH", image: "./images/level1/kuh.png" },
  { name: "OHR", image: "./images/level1/ohr.png" },
  { name: "NASE", image: "./images/level1/nase.png" },
  { name: "EULE", image: "./images/level1/eule.png" },
  { name: "ROT", image: "./images/level1/rot.png" },
  { name: "BALL", image: "./images/level1/ball.png" },
  { name: "BLAU", image: "./images/level1/blau.png" },
  { name: "AUTO", image: "./images/level1/auto.png" },
  { name: "HAND", image: "./images/level1/hand.png" },

  { name: "TOR", image: "./images/level1/tor.png" },
  { name: "BAUM", image: "./images/level1/baum.png" },
  { name: "BABY", image: "./images/level1/baby.png" },
  { name: "BUCH", image: "./images/level1/buch.png" },
  { name: "HAUS", image: "./images/level1/haus.png" },
  { name: "GANS", image: "./images/level1/gans.png" },
  { name: "GELD", image: "./images/level1/geld.png" },
  { name: "MAUS", image: "./images/level1/maus.png" },
  { name: "BROT", image: "./images/level1/brot.png" },
  { name: "HERZ", image: "./images/level1/herz.png" },

  { name: "MUND", image: "./images/level1/mund.png" },
  { name: "KEKS", image: "./images/level1/keks.jpg" },
  { name: "KANU", image: "./images/level1/kanu.jpeg" },
  { name: "GELD", image: "./images/level1/gelb.jpg" },
  { name: "HASE", image: "./images/level1/hase.png" },
  { name: "PFAU", image: "./images/level1/pfau.jpg" },
  { name: "LUPE", image: "./images/level1/lupe.png" },
  { name: "BOOT", image: "./images/level1/boot.jpg" },
  { name: "MAIS", image: "./images/level1/mais.jpeg" },
  { name: "DREI", image: "./images/level1/drei.jpg" },
]
var possibleWords2 = [
  { name: "KUCHEN", image: "./images/level2/kuchen.png" },
  { name: "BIENE", image: "./images/level2/biene.png" },
  { name: "FUCHS", image: "./images/level2/fuchs.png" },
  { name: "HAARE", image: "./images/level2/haare.png" },
  { name: "TASSE", image: "./images/level2/tasse.png" },
  { name: "FISCH", image: "./images/level2/fisch.png" },
  { name: "SONNE", image: "./images/level2/sonne.png" },
  { name: "MILCH", image: "./images/level2/milch.png" },
  { name: "FLAGGE", image: "./images/level2/flagge.png" },
  { name: "KATZE", image: "./images/level2/katze.png" },

  { name: "STERN", image: "./images/level2/stern.png" },
  { name: "PFERD", image: "./images/level2/pferd.png" },
  { name: "WASSER", image: "./images/level2/wasser.png" },
  { name: "ZEBRA", image: "./images/level2/zebra.png" },
  { name: "BLUME", image: "./images/level2/blume.png" },
  { name: "KREUZ", image: "./images/level2/kreuz.png" },
  { name: "WOLKE", image: "./images/level2/wolke.png" },
  { name: "APFEL", image: "./images/level2/apfel.png" },
  { name: "STUHL", image: "./images/level2/stuhl.png" },
  { name: "HANDY", image: "./images/level2/handy.png" },

  { name: "PAPIER", image: "./images/level2/papier.png" },
  { name: "FLUSS", image: "./images/level2/fluss.png" },
  { name: "KRONE", image: "./images/level2/krone.png" },
  { name: "KIRCHE", image: "./images/level2/kirche.png" },
  { name: "PALME", image: "./images/level2/palme.png" },
  { name: "ZAHLEN", image: "./images/level2/zahlen.png" },
  { name: "BRILLE", image: "./images/level2/brille.png" },
  { name: "LEHRER", image: "./images/level2/lehrer.png" },
  { name: "DELFIN", image: "./images/level2/delfin.png" },
  { name: "TEDDY", image: "./images/level2/teddy.png" },
]

var possibleWords3 = [
  { name: "SCHWEIN", image: "./images/level3/schwein.png" },
  { name: "BAUERNHOF", image: "./images/level3/bauernhof.png" },
  { name: "POLIZEI", image: "./images/level3/polizei.png" },
  { name: "ROBOTER", image: "./images/level3/roboter.png" },
  { name: "SCHLANGE", image: "./images/level3/schlange.png" },
  { name: "SCHNECKE", image: "./images/level3/schnecke.png" },
  { name: "KIRSCHE", image: "./images/level3/kirsche.png" },
  { name: "SPIEGEL", image: "./images/level3/spiegel.png" },
  { name: "FLUGZEUG", image: "./images/level3/flugzeug.png" },
  { name: "SCHWARZ", image: "./images/level3/schwarz.png" },

  { name: "BATTERIE", image: "./images/level3/batterie.png" },
  { name: "DRUCKER", image: "./images/level3/drucker.png" },
  { name: "GIRAFFE", image: "./images/level3/giraffe.png" },
  { name: "SECHZEHN", image: "./images/level3/sechzehn.png" },
  { name: "BASEBALL", image: "./images/level3/baseball.png" },
  { name: "KALENDAR", image: "./images/level3/kalendar.png" },
  { name: "COMPUTER", image: "./images/level3/computer.png" },
  { name: "ACHTZEHN", image: "./images/level3/achtzehn.png" },
  { name: "FUSSBALL", image: "./images/level3/fussball.png" },
  { name: "DREIZEHN", image: "./images/level3/dreizehn.png" },

  { name: "ELEFANT", image: "./images/level3/elefant.png" },
  { name: "PINGUIN", image: "./images/level3/pinguin.png" },
  { name: "SPAGHETTI", image: "./images/level3/spaghetti.png" },
  { name: "BALLON", image: "./images/level3/ballon.png" },
  { name: "FENSTER", image: "./images/level3/fenster.png" },
  { name: "SECHZIG", image: "./images/level3/sechzig.png" },
  { name: "GESCHENK", image: "./images/level3/geschenk.png" },
  { name: "BROKKOLI", image: "./images/level3/brokkoli.png" },
  { name: "NIKOLAUS", image: "./images/level3/nikolaus.png" },
  { name: "KLAVIER", image: "./images/level3/klavier.png" },
]


